### ISSUE TITLE
Setup an automated compiler workflow

### ISSUE THREAD

**Issue by clod44** [auth-xyz/clicky#1]
I heard you can set up a GitHub action to compile your code and show it as a released version whenever there is a change.

**Comment by auth-xyz** [comment]
it's a pain in the ass thrash.
also I have no clue how 2 do it

**Comment by clod44** [comment]
the + in C represents your struggle

**Comment by auth-xyz** [comment]
> the + in C represents your struggle

and the other represents your lack of potential
