### ISSUE TITLE
Improve build system!

### ISSUE THREAD

**Issue by lagoon107** [auth-xyz/clicky#2]
This is more of a suggestion, but please use a proper (or modern) build system. 
As this project grows, Makefiles can simply become confusing garbage. 
I would highly recommend using **Cmake or Meson** as your build system here.

Not only would using a proper build system simply make the developer's lives easier, but it would also allow other projects to **easily** use this library in their projects.

**Comment by auth-xyz** [comment]
Sorry for the late reply, but I'll make sure to do that!
I really want to have an automatic release system aswell, but I'll put that as a priority!
